### ISSUE TITLE
Get Auto Code working

### ISSUE THREAD

**Issue by arihant2math** [The-Knights-of-Ni/FreightFrenzy#59]
- [x] Determine corresponding level on shipping hub (Left is 1, Middle is 2, Right is 3) & drop in freight
- [x] Assume start on position closest to carousels.
- [x] Go to the Carousel
- [x] Deliver duck from carousel
- [x] Go to the shipping hub
- [x] Edit constants for delivering freight into hub (deploy, move towards hub, place, etc.)
- [x] Go to warehouse
- [x] Park in warehouse (completely)
- [x] #65

**Comment by moogloof** [comment]
Only thing left is delivering freight

**Comment by albonec** [comment]
we're done here no?
