### ISSUE TITLE
Automate the Hub Delivery System

### ISSUE THREAD

**Issue by arihant2math** [The-Knights-of-Ni/FreightFrenzy#69]
- [x] Ensure multithreading works properly
- [x] Ensure servos are logically connected
- [x] Variable motor speed for linear slide
- [x] Tune time constant to open servo at bottom

**Comment by moogloof** [comment]
- [ ] Test movement towards the hub.
- [ ] Test deployment of slide.
- [ ] Ensure that threading works properly.
- [ ] Ensure that servos are logically connected.

**Comment by Rlin232** [comment]
Now we have to do the variable power, so we can adjust the time constant before reopening the lid at the bottom of the motion
